Repository LmeSzinc/StarRailCopilot, pull requests merged in 2023-10, with the labels that each got.

#142 Opt: Detailed shadow name in configs
  dev_tools/keyword_extract.py
  module/config/config_updater.py
  module/config/i18n/en-US.json
  module/config/i18n/es-ES.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  tasks/dungeon/keywords/__init__.py
  tasks/dungeon/keywords/classes.py
  tasks/dungeon/keywords/dungeon_detailed.py
Labels: optimization / 优化

#153 Fix: Loop call of update_battle_pass_quests
  tasks/battle_pass/battle_pass.py
Labels: bug / 缺陷

#141 Add: Ocr and select rogue event options
  assets/share/rogue/event/OCR_EVENT.png
  assets/share/rogue/event/OCR_OPTION.png
  assets/share/rogue/event/OCR_TITLE.png
  assets/share/rogue/event/OPTION_SCROLL.png
  assets/share/rogue/event/REST_AREA.png
  dev_tools/keyword_extract.py
  module/ocr/keyword.py
  tasks/rogue/assets/assets_rogue_event.py
  tasks/rogue/bleesing/blessing.py
  tasks/rogue/event/event.py
  tasks/rogue/event/preset.py
  tasks/rogue/keywords/__init__.py
  tasks/rogue/keywords/classes.py
  tasks/rogue/keywords/event_option.py
  tasks/rogue/keywords/event_title.py
  tasks/rogue/route/base.py
Labels: feature request / 功能请求

#155 Add: Get Support Reward Everyday
  assets/character/Jingliu.png
  assets/cn/freebies/support_reward/PROFILE.png
  assets/share/freebies/support_reward/CAN_GET_REWARD.png
  assets/share/freebies/support_reward/CLICKING_REWARD.png
  assets/share/freebies/support_reward/IN_PROFILE.png
  assets/share/freebies/support_reward/MENU_TO_PROFILE.png
  config/template.json
  dev_tools/keyword_extract.py
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/argument/default.yaml
  module/config/argument/menu.json
  module/config/argument/task.yaml
  module/config/config_generated.py
  module/config/config_manual.py
  module/config/config_updater.py
  module/config/i18n/en-US.json
  module/config/i18n/es-ES.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  src.py
  tasks/character/keywords/character_list.py
  tasks/dungeon/keywords/dungeon.py
  tasks/dungeon/keywords/dungeon_detailed.py
  tasks/freebies/assets/assets_freebies_support_reward.py
  tasks/freebies/freebies.py
  tasks/freebies/support_reward.py
  tasks/rogue/keywords/curio.py
Labels: feature request / 功能请求

#168 Opt: Clean rogue event options
  dev_tools/keyword_extract.py
  tasks/rogue/event/event.py
  tasks/rogue/event/preset.py
  tasks/rogue/keywords/event_option.py
  tasks/rogue/keywords/event_title.py
Labels: optimization / 优化

#169 Fix: Redispatch directly if possible
  tasks/assignment/assignment.py
Labels: bug / 缺陷
