Repository LmeSzinc/StarRailCopilot, pull requests merged in 2023-12, with the labels that each got.

#198 Upd: Use DraggableList to rewrite choose rogue path and add propagation in rogue
  assets/cn/rogue/path/PAGE_ROGUE_PATH.png
  assets/en/rogue/path/PAGE_ROGUE_PATH.png
  assets/share/rogue/path/CHECK_PROPAGATION.png
  assets/share/rogue/path/CHOOSE_LEFT.png
  assets/share/rogue/path/CHOOSE_RIGHT.png
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/es-ES.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  tasks/rogue/assets/assets_rogue_path.py
  tasks/rogue/entry/path.py
  tasks/rogue/keywords/classes.py
Labels: good first issue / 首次贡献, feature request / 功能请求

#224 Upd: Add filter preset extract
  dev_tools/filter_preset_extract.py
  tasks/rogue/blessing/blessing.py
  tasks/rogue/blessing/curio.py
  tasks/rogue/blessing/preset.py
Labels: feature request / 功能请求

#227 Fix: is_curio_selected()
  assets/share/rogue/curio/CURIO_SELECTED.png
  tasks/rogue/assets/assets_rogue_curio.py
  tasks/rogue/blessing/curio.py
Labels: bug / 缺陷

#235 Upd: Character
  assets/character/RuanMei.png
  assets/character/Xueyi.png
  assets/share/base/page/ROGUE_CHECK.png
  assets/share/rogue/entry/OCR_WORLD.png
  assets/share/rogue/path/CHECK_ABUNDANCE.png
  assets/share/rogue/path/CHECK_DESTRUCTION.png
  assets/share/rogue/path/CHECK_ELATION.png
  assets/share/rogue/path/CHECK_NIHILITY.png
  assets/share/rogue/path/CHECK_PRESERVATION.png
  assets/share/rogue/path/CHECK_THE_HUNT.png
  assets/share/rogue/path/CLICK_REMEMBRANCE.png
  assets/share/rogue/path/CONFIRM_PATH.BUTTON.png
  assets/share/rogue/path/CONFIRM_PATH.png
  assets/share/rogue/weekly/REWARD_ENTER.BUTTON.png
  assets/share/rogue/weekly/REWARD_ENTER.png
  config/template.json
  dev_tools/keyword_extract.py
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/config_updater.py
  module/config/i18n/en-US.json
  module/config/i18n/es-ES.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  tasks/assignment/assignment.py
  tasks/base/assets/assets_base_page.py
  tasks/battle_pass/keywords/quest.py
  tasks/character/keywords/character_list.py
  tasks/character/keywords/height.py
  tasks/daily/daily_quest.py
  tasks/daily/keywords/daily_quest.py
  tasks/dungeon/dungeon.py
  tasks/dungeon/keywords/dungeon.py
  tasks/dungeon/keywords/dungeon_detailed.py
  tasks/dungeon/ui.py
  tasks/rogue/assets/assets_rogue_entry.py
  tasks/rogue/assets/assets_rogue_path.py
  tasks/rogue/assets/assets_rogue_weekly.py
  tasks/rogue/blessing/bonus.py
  tasks/rogue/keywords/bonus.py
  tasks/rogue/keywords/curio.py
  tasks/rogue/keywords/event_option.py
  tasks/rogue/keywords/event_title.py
  tasks/rogue/keywords/path.py
  tasks/rogue/keywords/resonance.py
  tasks/rogue/rogue.py
Labels: assets issue / 资源适配问题

#251 fix: combat support COMBAT_SUPPORT_LIST repeat triggering
  tasks/combat/support.py
Labels: bug / 缺陷
