Repository LmeSzinc/StarRailCopilot, pull requests merged in 2023-09, with the labels that each got.

#58 Add: rogue buff selector
  assets/share/rogue/blessing/BLESSING_ENFORCE.png
  assets/share/rogue/blessing/BLESSING_RESET.png
  assets/share/rogue/blessing/BLESSING_STABLE_FLAG.png
  assets/share/rogue/blessing/BOTTOM_WHITE_BAR.png
  assets/share/rogue/blessing/OCR_RESET_COST.png
  assets/share/rogue/blessing/OCR_RESET_COUNT.png
  assets/share/rogue/blessing/OCR_ROGUE_BUFF.png
  assets/share/rogue/bonus/BONUS_BOTTOM_WHITE_BAR.png
  assets/share/rogue/bonus/BONUS_CONFIRM.png
  assets/share/rogue/curio/CURIO_ENFORCE.png
  assets/share/rogue/curio/OCR_ROGUE_CURIO.png
  assets/share/rogue/ui/BLESSING_CONFIRM.png
  assets/share/rogue/ui/CHECK_BLESSING.png
  assets/share/rogue/ui/COSMIC_FRAGMENT.png
  assets/share/rogue/ui/FLAG_UNRECORD.png
  assets/share/rogue/ui/OBTAIN_ITEM_POPUP.png
  assets/share/rogue/ui/OCR_COSMIC_FRAGMENT.png
  assets/share/rogue/ui/PAGE_CHOOSE_BONUS.png
  assets/share/rogue/ui/PAGE_CHOOSE_BUFF.png
  assets/share/rogue/ui/PAGE_CHOOSE_CURIO.png
  assets/share/rogue/ui/PAGE_EVENT.png
  config/template.json
  dev_tools/keyword_extract.py
  module/base/filter.py
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/argument/menu.json
  module/config/argument/task.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/ocr/keyword.py
  tasks/rogue/assets/assets_rogue_blessing.py
  tasks/rogue/assets/assets_rogue_bonus.py
  tasks/rogue/assets/assets_rogue_curio.py
  tasks/rogue/assets/assets_rogue_ui.py
  tasks/rogue/blessing.py
  tasks/rogue/bonus.py
  tasks/rogue/curio.py
  tasks/rogue/keywords/__init__.py
  tasks/rogue/keywords/blessing.py
  tasks/rogue/keywords/bonus.py
  tasks/rogue/keywords/classes.py
  tasks/rogue/keywords/curio.py
  tasks/rogue/keywords/enhancement.py
  tasks/rogue/keywords/path.py
  tasks/rogue/keywords/resonance.py
  tasks/rogue/preset.py
  tasks/rogue/selector.py
  tasks/rogue/ui.py
  tasks/rogue/utils.py
Labels: feature request / 功能请求

#63 detector for enemy and item
  tasks/combat/detector.py
Labels: good first issue / 首次贡献, feature request / 功能请求

#89 Fix: Assignments missing groups
  module/ui/draggable_list.py
  tasks/assignment/keywords/__init__.py
  tasks/assignment/ui.py
Labels: bug / 缺陷

#109 Feature: Adds Spanish language to SRC
  module/config/i18n/es-ES.json
  webapp/packages/renderer/src/locales/lang/es-ES.json
Labels: documentation / 文档, good first issue / 首次贡献

#112 Feature: Added Spanish translation of the README
  README.md
  README_en.md
  README_es.md
  doc/README.assets/gui_es.png
  module/device/platform/emulator_windows.py
Labels: documentation / 文档

#114 Fix: Text mistake
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
Labels: good first issue / 首次贡献
