Repository LmeSzinc/StarRailCopilot, pull requests merged in 2023-11, with the labels that each got.

#183 Fix: expiration time comparison in StoredExpiredAtMonday0400
  module/config/utils.py
Labels: bug / 缺陷, good first issue / 首次贡献

#196 Fix: OCR_LEVEL in BattlePass
  assets/share/battle_pass/OCR_LEVEL.png
  module/config/config.py
  tasks/battle_pass/assets/assets_battle_pass.py
  tasks/battle_pass/battle_pass.py
Labels: assets issue / 资源适配问题

#200 Update support.py
  tasks/combat/support.py
Labels: bug / 缺陷, good first issue / 首次贡献

#204 Fix: enter forgottenhall if seats are full
  assets/share/forgotten_hall/ui/SEAT_1.png
  assets/share/forgotten_hall/ui/SEAT_2.png
  assets/share/forgotten_hall/ui/SEAT_3.png
  assets/share/forgotten_hall/ui/SEAT_4.png
  tasks/forgotten_hall/assets/assets_forgotten_hall_ui.py
  tasks/forgotten_hall/team.py
Labels: bug / 缺陷
