Repository LmeSzinc/StarRailCopilot, pull requests merged in 2024-04, with the labels that each got.

#414 Fix: More tolerant insight_row
  assets/share/dungeon/event/OCR_DOUBLE_ROGUE_REMAIN.png
  module/ui/draggable_list.py
  tasks/dungeon/assets/assets_dungeon_event.py
  tasks/dungeon/dungeon.py
  tasks/dungeon/event.py
Labels: bug / 缺陷

#361 Add feature of material farming in task RogueWorld
  config/template.json
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/argument/stored.json
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/es-ES.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/config/stored/classes.py
  module/config/stored/stored_generated.py
  tasks/map/control/control.py
  tasks/rogue/entry/entry.py
  tasks/rogue/route/base.py
Labels: good first issue / 首次贡献, feature request / 功能请求

#418 Feature: Migrate notify.py from AzurLaneAutoScript and upgrade dep onepush ver. to 1.3.0
  module/notify.py
  requirements-in.txt
  requirements.txt
Labels: good first issue / 首次贡献, feature request / 功能请求

#424 Fix: Global MuMu 12 id
  module/device/platform/emulator_base.py
Labels: bug / 缺陷, good first issue / 首次贡献

#430 Fix custom resonance filter errors
  tasks/rogue/blessing/blessing.py
Labels: bug / 缺陷
