Repository LmeSzinc/StarRailCopilot, pull requests merged in 2024-07, with the labels that each got.

#572 Fix: ocr scan chinese '方相果实' to replace '万相果实'
  tasks/planner/scan.py
Labels: bug / 缺陷

#551 Add: use fuel & extract trailblaze power
  assets/share/combat/prepare/EXTRACT_RESERVED_TRAILBLAZE_POWER.png
  assets/share/combat/prepare/FUEL.png
  assets/share/combat/prepare/FUEL_ENTRANCE.png
  assets/share/combat/prepare/FUEL_MINUS.png
  assets/share/combat/prepare/FUEL_PLUS.png
  assets/share/combat/prepare/FUEL_SELECTED.SEARCH.png
  assets/share/combat/prepare/FUEL_SELECTED.png
  assets/share/combat/prepare/FUEL_SLIDER.png
  assets/share/combat/prepare/OCR_EXTRACT_RESERVED_TRAILBLAZE_POWER_COUNT.png
  assets/share/combat/prepare/OCR_FUEL.png
  assets/share/combat/prepare/OCR_FUEL_COUNT.png
  assets/share/combat/prepare/OCR_RESERVED_TRAILBLAZE_POWER.png
  assets/share/combat/prepare/RESERVED_MINUS.png
  assets/share/combat/prepare/RESERVED_PLUS.png
  assets/share/combat/prepare/RESERVED_SLIDER.png
  assets/share/combat/prepare/RESERVED_TRAILBLAZE_POWER_ENTRANCE.png
  assets/share/combat/prepare/USING_FUEL.png
  config/template.json
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/argument/task.yaml
  module/config/config_generated.py
  module/config/config_updater.py
  module/config/i18n/en-US.json
  module/config/i18n/es-ES.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  tasks/combat/assets/assets_combat_prepare.py
  tasks/combat/combat.py
  tasks/combat/fuel.py
Labels: feature request / 功能请求

#596 Upd: Character
  assets/character/Jade.png
  assets/character/Yunli.png
  module/config/argument/args.json
  module/config/config_updater.py
  module/config/i18n/en-US.json
  module/config/i18n/es-ES.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
Labels: assets issue / 资源适配问题
