Repository LmeSzinc/StarRailCopilot, pull requests merged in 2024-06, with the labels that each got.

#504 Change `Alas` to `Src` in notify push to avoid confusing
  module/alas.py
Labels: optimization / 优化

#503 Fix login task stuck when render error
  tasks/base/ui.py
  tasks/login/login.py
Labels: assets issue / 资源适配问题

#516 合成角色养成材料 | Synthesize meterials from character planner
  assets/share/combat/obtain/ITEM_NAME.png
  assets/share/combat/prepare/WAVE_SLIDER.png
  assets/share/item/synthesize/SYNTHESIZE_CONFIRM.png
  assets/share/item/synthesize/SYNTHESIZE_SLIDER.png
  assets/share/item/ui/SWITCH_CLICK.png
  assets/share/item/ui/SWITCH_SEARCH.png
  module/config/config.py
  module/config/config_manual.py
  module/ui/scroll.py
  module/ui/switch.py
  tasks/battle_pass/battle_pass.py
  tasks/combat/assets/assets_combat_obtain.py
  tasks/combat/assets/assets_combat_prepare.py
  tasks/combat/prepare.py
  tasks/dungeon/dungeon.py
  tasks/dungeon/event.py
  tasks/dungeon/weekly.py
  tasks/item/assets/assets_item_synthesize.py
  tasks/item/assets/assets_item_ui.py
  tasks/item/data_update.py
  tasks/item/relics.py
  tasks/item/slider.py
  tasks/item/synthesize.py
  tasks/item/ui.py
  tasks/planner/model.py
  tasks/rogue/rogue.py
Labels: feature request / 功能请求

#530 Fix keyword_extract and i18n
  config/template.json
  dev_tools/keyword_extract.py
  dev_tools/keywords/base.py
  dev_tools/keywords/map_plane.py
  module/config/argument/args.json
  module/config/argument/stored.json
  module/config/config_generated.py
  module/config/config_updater.py
  module/config/i18n/en-US.json
  module/config/i18n/es-ES.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/config/stored/stored_generated.py
  tasks/battle_pass/battle_pass.py
  tasks/battle_pass/keywords/quest.py
  tasks/character/keywords/character_list.py
  tasks/daily/keywords/daily_quest.py
  tasks/dungeon/keywords/dungeon.py
  tasks/dungeon/keywords/dungeon_detailed.py
  tasks/planner/keywords/item_trace.py
  tasks/rogue/event/event.py
  tasks/rogue/event/preset.py
  tasks/rogue/keywords/blessing.py
  tasks/rogue/keywords/bonus.py
  tasks/rogue/keywords/curio.py
  tasks/rogue/keywords/event_option.py
  tasks/rogue/keywords/event_title.py
  tasks/rogue/rogue.py
Labels: assets issue / 资源适配问题
