Repository LmeSzinc/StarRailCopilot, pull requests merged in 2024-05, with the labels that each got.

#441 Update data_update.py for removing whitespace in credit ocr result
  tasks/item/data_update.py
Labels: bug / 缺陷

#442 Fix: Add handle_blessing_popup in blessing choosing
  tasks/rogue/blessing/blessing.py
Labels: bug / 缺陷

#419 Apply StoredCounter for counting farm times
  assets/gui/css/dark-alas.css
  assets/gui/css/light-alas.css
  config/template.json
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/argument/stored.json
  module/config/config_generated.py
  module/config/config_updater.py
  module/config/convert.py
  module/config/i18n/en-US.json
  module/config/i18n/es-ES.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/config/stored/classes.py
  module/config/stored/stored_generated.py
  module/webui/widgets.py
  tasks/rogue/entry/entry.py
  tasks/rogue/route/base.py
Labels: optimization / 优化

#447 Upd: Add new dungeon and weekly in gui by config updater
  dev_tools/keywords/map_plane.py
  module/config/argument/args.json
  module/config/config_generated.py
  module/config/config_updater.py
  module/config/i18n/en-US.json
  module/config/i18n/es-ES.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  tasks/assignment/ui.py
  tasks/dungeon/ui.py
  tasks/map/keywords/plane.py
Labels: assets issue / 资源适配问题

#464 Fix: Obtain position & closed
  assets/cn/combat/obtain/MAY_OBTAIN.SEARCH.png
  assets/cn/combat/obtain/MAY_OBTAIN.png
  assets/en/combat/obtain/MAY_OBTAIN.SEARCH.png
  assets/en/combat/obtain/MAY_OBTAIN.png
  tasks/combat/assets/assets_combat_obtain.py
  tasks/combat/obtain.py
Labels: bug / 缺陷

#469 Fix: Ensure assignment entry loaded
  tasks/assignment/assignment.py
  tasks/assignment/ui.py
Labels: bug / 缺陷

#471 Fix: Check EVENT_FINISHED
  assets/cn/assignment/ui/EVENT_FINISHED.png
  tasks/assignment/assets/assets_assignment_ui.py
  tasks/assignment/claim.py
  tasks/assignment/ui.py
Labels: bug / 缺陷

#475 Fix: Clear content of ASSIGNMENT_ENTRY_LIST if needed
  assets/cn/assignment/ui/EVENT_COMPLETED.png
  assets/en/assignment/ui/EVENT_COMPLETED.png
  tasks/assignment/assets/assets_assignment_ui.py
  tasks/assignment/assignment.py
  tasks/assignment/claim.py
  tasks/assignment/ui.py
Labels: bug / 缺陷, assets issue / 资源适配问题

#488 Upd: Character
  assets/character/Boothill.png
  module/config/argument/args.json
  module/config/config_generated.py
  module/config/config_updater.py
  module/config/i18n/en-US.json
  module/config/i18n/es-ES.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
Labels: assets issue / 资源适配问题
